package com.david.pokedex_pruebas.modelo

import com.david.pokedex_pruebas.R
import java.util.Locale

data class PokemonOld(
    var foto: Int=0,
    var name: String="",
    var desc: String=""
)

var listaPoke : List<PokemonOld> = listOf(
    PokemonOld((R.drawable.bulbasaur01), "Bulbasaur", "Puede sobrevivir largo tiempo sin probar bocado. Guarda energía en el bulbo de su espalda.")
    , PokemonOld((R.drawable.ivisaur01), "Ivysaur", "Su bulbo crece cuando absorbe energía. Desprende un fuerte aroma cuando florece.")
    , PokemonOld((R.drawable.venusaur01), "Venusaur", "La flor de su espalda recoge los rayos del sol. Los transforma en energía.")
    , PokemonOld((R.drawable.charmander01), "Charmander", "La llama en la punta de su cola chisporrotea al arder. Sólo se oye en lugares silenciosos.")
    , PokemonOld((R.drawable.charmeleon01), "Charmeleon", "Las duras luchas excitan a este Pokémon. Entonces, lanzará llamaradas blanco-azuladas.")
    , PokemonOld((R.drawable.charizard01), "Charizard", "Cuando lanza una descarga de fuego súper caliente, la roja llama de su cola brilla más intensamente.")
    , PokemonOld((R.drawable.squirtle01), "Squirtle", "Lanza agua a su presa desde el agua. Se esconde en su concha cuando se siente en peligro.")
    , PokemonOld((R.drawable.wartortle01), "Wartortle", "Si es golpeado, esconderá su cabeza. Aun así, su cola puede seguir golpeando.")
    , PokemonOld((R.drawable.blastoise01), "Blastoise", "Cuando ataca a un enemigo, su descarga de agua es aún más potente que una manga de bombero.")
    , PokemonOld((R.drawable.caterpie01), "Caterpie", "Si tocas los receptores de su cabeza, soltará un terrible olor para protegerse.")
    , PokemonOld((R.drawable.metapod01), "Metapod", "Endurece su concha para protegerse. De todos modos, un gran impacto puede afectarle.")
    , PokemonOld((R.drawable.butterfree01), "Butterfree", "Sus alas están cubiertas de polvos venenosos. Como repelen el agua, puede volar bajo la lluvia.")
    , PokemonOld((R.drawable.weedle01), "Weedle", "Cuidado con el aguijón venenoso de su cabeza. Se esconde en la hierba y arbustos mientras come.")
    , PokemonOld((R.drawable.kakuna01), "Kakuna", "Sólo puede moverse un poco. Cuando está en peligro, envenena a su enemigo con su aguijón.")
    , PokemonOld((R.drawable.beedril01), "Beedril", "Tiene 3 aguijones venenosos en sus patas y cola. Suele pinchar a sus enemigos repetidas veces.")
    , PokemonOld((R.drawable.pidgey), "Pidgey", "Son muy dóciles. Si son atacados, suelen lanzar arena en lugar de repeler el ataque.")
    , PokemonOld((R.drawable.pidgeotto), "Pidgeotto", "Su visión es extraordinaria. Aunque vuele muy alto, detectará todo movimiento de su presa.")
    , PokemonOld((R.drawable.pidgeot), "Pidgeot", "Este Pokémon vuela a velocidad Mach 2. Sus grandes garras son armas muy peligrosas.")
    , PokemonOld((R.drawable.rattata), "Rattata", "Muerde cualquier cosa con sus colmillos. Si ves uno, seguro que encuentras 40 más en la zona.")
    , PokemonOld((R.drawable.raticate), "Raticate", "Sus patas son palmeadas. Sirven de aletas, por lo que puede nadar por ríos en busca de presa.")
    , PokemonOld((R.drawable.spearow), "Spearow", "Es incapaz de volar a gran altura, pero es muy rápido, lo que le permite protegerse.")
    , PokemonOld((R.drawable.fearow), "Fearow", "Este Pokémon es conocido desde hace muchos años. Si siente peligro volará lejos inmediatamente.")
    , PokemonOld((R.drawable.ekans), "Ekans", "Cuanto más viejo, más crece este Pokémon. Por la noche, descansa en las ramas de los árboles.")
    , PokemonOld((R.drawable.arbok), "Arbok", "Los espantosos dibujos de su piel han sido estudiados. Seis variaciones han sido confirmadas.")
    , PokemonOld((R.drawable.pikachu), "Pikachu", "Mantiene su cola en alto para vigilar. Si das un tirón a su cola, querrá morderte.")
    , PokemonOld((R.drawable.raichu), "Raichu", "Cuando la electricidad del cuerpo crece, se vuelve irritable. También brilla en la oscuridad.")
    , PokemonOld((R.drawable.sandshrew), "Sandshrew", "Su cuerpo es muy seco. Cuando hace frío por la noche, su piel aparece cubierta con un fino rocío.")
    , PokemonOld((R.drawable.sandslash), "Sandslash", "Es muy hábil al golpear a sus enemigos con sus garras. Si se rompen, crecerán en un solo día.")
    , PokemonOld((R.drawable.nidoranf), "Nidoran F", "A este Pokémon no le gusta luchar. Pero cuidado, sus pequeños cuernos segregan veneno.")
    , PokemonOld((R.drawable.nidorina), "Nidorina", "Cuando descansa profundamente, sus cuernos se contraen. Esto prueba que está relajado.")
    , PokemonOld((R.drawable.nidoqueen), "Nidoqueen", "Grandes escamas recubren el duro cuerpo de este Pokémon. Éstas crecen cíclicamente.")
    , PokemonOld((R.drawable.nidoranm), "Nidoran M", "Sus largas orejas se mantienen siempre alerta. Si siente peligro, atacará con su venenoso cuerno.")
    , PokemonOld((R.drawable.nidorino), "Nidorino", "Sus cuernos contienen veneno. Si se introducen en el cuerpo del enemigo, soltarán su tóxica carga.")
    , PokemonOld((R.drawable.nidoking), "Nidoking", "Duro como el acero, posee una poderosa carga. Sus cuernos son tan duros como el diamante.")
    , PokemonOld((R.drawable.clefairy), "Clefairy", "Su aspecto jovial y vivaracho lo hace adorable. Piensan que son raros, ya que no son muy comunes.")
    , PokemonOld((R.drawable.clefable), "Clefable", "Protege bastante bien su propio entorno. Es una especie de hada, raramente vista por los humanos.")
    , PokemonOld((R.drawable.vulpix), "Vulpix", "Su piel y colas son preciosas. Cuando crecen las colas, se dividen formando nuevas colas.")
    , PokemonOld((R.drawable.ninetales), "Ninetales", "De acuerdo con una antigua leyenda, este Pokémon es la reencarnación de 9 nobles santos.")
    , PokemonOld((R.drawable.jigglypuff), "Jigglypuff", "Utiliza sus misteriosos ojos para engañar a su enemigo. También cantará para dormirlo.")
    , PokemonOld((R.drawable.wigglytuff), "Wigglytuff", "Su cuerpo es muy elástico. Cuando inhala aire profundamente, puede inflarse sin límite.")
    , PokemonOld((R.drawable.zubat), "Zubat", "Emite sonidos ultrasónicos mientras vuela. Los utiliza como sónar para evitar obstáculos.")
    , PokemonOld((R.drawable.golbat), "Golbat", "Ataca de manera violenta sin avisar. Utiliza sus afilados colmillos para chupar sangre.")
    , PokemonOld((R.drawable.oddish), "Oddish", "Suele ser confundido con un puñado de semillas. Si lo extraes del suelo, gritará.")
    , PokemonOld((R.drawable.gloom), "Gloom", "¡Huele bastante mal! De todas formas, 1 de cada 1000 personas aprecian su fétido olor.")
    , PokemonOld((R.drawable.vileplume), "Vileplume", "Aletea sus pétalos de flores para propagar su venenoso polen. El sonido que emite es agudo.")
    , PokemonOld((R.drawable.paras), "Paras", "Escarba bajo el suelo para roer las raíces de los árboles. Sus setas absorben sus energías.")
    , PokemonOld((R.drawable.parasect), "Parasect", "El parásito absorbe la energía con las setas de la espalda, que lo controlan.")
    , PokemonOld((R.drawable.venonat), "Venonat", "Sus grandes ojos actúan como radares. En lugares claros, verás montones de pequeños ojos.")
    , PokemonOld((R.drawable.venomoth), "Venomoth", "Es difícil quitar el polvo de sus alas. También posee un veneno que se desprende al contacto.")
    , PokemonOld((R.drawable.diglett), "Diglett", "Prefiere los lugares oscuros. Pasa el tiempo bajo tierra, aunque aparece en cuevas.")
    , PokemonOld((R.drawable.dugtrio), "Dugtrio", "Un grupo de trillizos que cava a 90 KPH. Por ello, creen que se trata de un terremoto.")
    , PokemonOld((R.drawable.meowth), "Meowth", "Parece que son más activos por la noche. Adoran las cosas redondas y brillantes.")
    , PokemonOld((R.drawable.persian), "Persian", "¡La gema en su frente brilla por sí misma! Camina con la elegancia de una reina.")
    , PokemonOld((R.drawable.psyduck), "Psyduck", "Siempre tiene dolores de cabeza. Posee poderes mentales, pero no sabes cuándo los usará.")
    , PokemonOld((R.drawable.golduck), "Golduck", "Sus delgados y largos miembros acaban en anchas aletas. Las usan para nadar en los lagos.")
    , PokemonOld((R.drawable.mankey), "Mankey", "Este ágil Pokémon vive en los arboles. Se enfada fácilmente y no dudará en atacar a todos.")
    , PokemonOld((R.drawable.primeape), "Primeape", "Sólo se calma cuando nadie está cerca. Llegar a ver ese momento es realmente difícil.")
    , PokemonOld((R.drawable.growlithe), "Growlithe", "Este Pokémon es muy amistoso. Aun así, gruñirá a cualquiera que invada su territorio.")
    , PokemonOld((R.drawable.arcanine), "Arcanine", "Es un Pokémon legendario en China. Allí, adoran la gracia y belleza que exhibe al correr.")
    , PokemonOld((R.drawable.poliwag), "Poliwag", "La dirección de la espiral en el vientre cambia según el área. Prefiere nadar a correr.")
    , PokemonOld((R.drawable.poliwhirl), "Poliwhirl", "Cuando lo atacan, usa la espiral del vientre para dormir al rival. Aprovecha para escapar entonces.")
    , PokemonOld((R.drawable.poliwrath), "Poliwrath", "Es capaz de nadar usando todos los músculos de su cuerpo. Podrá adelantar incluso a un campeón.")
    , PokemonOld((R.drawable.abra), "Abra", "Duerme 18 horas al día. Si siente peligro, se teletransporta a un lugar seguro, aun durmiendo.")
    , PokemonOld((R.drawable.kadabra), "Kadabra", "Muchas cosas raras suceden si está cerca. Por ejemplo, hace que los relojes vayan al revés.")
    , PokemonOld((R.drawable.alakazam), "Alakazam", "Este Pokémon lo recuerda todo. Nunca olvida lo que aprende. Es un Pokémon muy listo.")
    , PokemonOld((R.drawable.machop), "Machop", "Muy poderoso a pesar de su pequeño tamaño. Su maestría en artes marciales lo hace muy duro.")
    , PokemonOld((R.drawable.machoke), "Machoke", "El cinturón que rodea su cintura retiene toda su energía. Sin él, este Pokémon sería implacable.")
    , PokemonOld((R.drawable.machamp), "Machamp", "Con sólo un brazo puede mover montañas. Usando los cuatro, este Pokémon puede ser terrible.")
    , PokemonOld((R.drawable.bellsprout), "Bellsprout", "Prefiere los lugares calientes y húmedos. Atrapa pequeños insectos con sus ramas para devorarlos.")
    , PokemonOld((R.drawable.weepinbell), "Weeperbell", "Cuando está hambriento, ataca a todo lo que se mueva. Su pobre presa se derrite en fuertes ácidos.")
    , PokemonOld((R.drawable.victreebel), "Victreebel", "Engaña a su presa con un dulce aroma a miel. Una vez atrapada, la presa perderá hasta sus huesos.")
    , PokemonOld((R.drawable.tentacool), "Tentacool", "A veces puede ser encontrado seco y medio enterrado en una playa. Al lanzarlo otra vez al mar revivirá.")
    , PokemonOld((R.drawable.tentacruel), "Tentacruel", "Puede controlar libremente sus 80 tentáculos. Éstos debilitan a la presa con su poderoso veneno.")
    , PokemonOld((R.drawable.geodude), "Geodude", "Se encuentran normalmente en los caminos de montaña. Si te cruzas con uno, se enfadará.")
    , PokemonOld((R.drawable.graveler), "Graveler", "Se le suele ver rodando por las montañas. Los obstáculos no los evita. ¡Los arrolla!")
    , PokemonOld((R.drawable.golem), "Golem", "Cuando pierde su piel, su cuerpo se vuelve blando y blanquecino. Si esto ocurre, se esconderá.")
    , PokemonOld((R.drawable.ponyta), "Ponyta", "Es capaz de saltar muy alto. Con sus pezuñas y sus robustas patas, absorbe el impacto.")
    , PokemonOld((R.drawable.rapidash), "Rapidash", "Le encanta correr. Si ve algo más rápido que él, intentará alcanzarlo a toda velocidad.")
    , PokemonOld((R.drawable.slowpoke), "Slowpoke", "Es increíblemente lento y perezoso. Le encanta dormir sin preocuparse ni del tiempo ni de lo que ocurra.")
    , PokemonOld((R.drawable.slowbro), "Slowbro", "Vive tranquilo en el mar. Si el Shellder de su cola se cae, vuelve a ser un Slowpoke otra vez.")
    , PokemonOld((R.drawable.magnemite), "Magnemite", "Puede desafiar a la gravedad desde su nacimiento. Flota en el aire gracias a ondas electromagnéticas.")
    , PokemonOld((R.drawable.magneton), "Magneton", "Genera extrañas señales de radio. Es capaz de elevar la temperatura 3º centígrados.")
    , PokemonOld((R.drawable.farfetchd), "Farfetch'd", "Vive cerca de las plantas. Son raramente vistos, así que se piensa que se están extinguiendo.")
    , PokemonOld((R.drawable.doduo), "Doduo", "Sus cortas alas lo hacen volar con dificultad. De todos modos, puede correr a gran velocidad.")
    , PokemonOld((R.drawable.dodrio), "Dodrio", "Una de las dos cabezas de Doduo se divide para formar un nuevo PkMn. Es capaz de correr a 40 KPH.")
    , PokemonOld((R.drawable.seel), "Seel", "A este Pokémon le encanta el frío. Le encanta nadar en climas polares, sea cual sea la temperatura.")
    , PokemonOld((R.drawable.dewgong), "Dewgong", "Su cuerpo es como una bola de nieve. Inmune al frío intenso, nada rápidamente en aguas heladas.")
    , PokemonOld((R.drawable.grimer), "Grimer", "Está hecho de fango endurecido. Huele a pútrido. ¡Por donde pasa, no crece la hierba!")
    , PokemonOld((R.drawable.muk), "Muk", "Huele tan mal que puede provocar desmayos. Ha degenerado tanto, que ya ni él mismo se huele.")
    , PokemonOld((R.drawable.shellder), "Shellder", "Su concha puede evitar cualquier ataque. El débil cuerpo sólo está expuesto cuando está abierta.")
    , PokemonOld((R.drawable.cloyster), "Cloyster", "Utiliza su concha para protegerse. Dicen que es más dura que el diamante. También lanza espinas.")
    , PokemonOld((R.drawable.gastly), "Gastly", "Solo aparece en edificios en ruinas. No tiene forma real, ya que parece que está hecho de gas.")
    , PokemonOld((R.drawable.haunter), "Haunter", "Toma la vida de su adversario a lengüetazos. Esto produce mareos hasta que la víctima fallece.")
    , PokemonOld((R.drawable.gengar), "Gengar", "Sabrás que un Gengar está cerca cuando sufras de sudores fríos. Intentará echarte un hechizo.")
    , PokemonOld((R.drawable.onix), "Onix", "Cava a gran velocidad en busca de comida. Los túneles que deja son usados por los Diglett.")
    , PokemonOld((R.drawable.drowzee), "Drowzee", "Si duermes cerca de uno todo el tiempo, en alguna ocasión podrás ver sueños que se haya comido antes.")
    , PokemonOld((R.drawable.hypno), "Hypno", "Intenta evitar cualquier tipo de contacto visual con este Pokémon. Puede hipnotizar con su péndulo.")
    , PokemonOld((R.drawable.krabby), "Krabby", "Sus pinzas son armas perfectas. En alguna ocasión pueden romperse en combate, pero crecerán rápido.")
    , PokemonOld((R.drawable.kingler), "Kingler", "Una de sus pinzas crece más que la otra, y es dura como el acero. De todos modos, pesa demasiado.")
    , PokemonOld((R.drawable.voltorb), "Voltorb", "Se dice que se camufla como una Poké Ball. Al más mínimo estímulo se autodestruirá.")
    , PokemonOld((R.drawable.electrode), "Electrode", "Almacena energía eléctrica en su cuerpo. El más leve shock puede provocar una gran explosión.")
    , PokemonOld((R.drawable.exeggcute), "Exeggcute", "Sus cabezas se atraen unas a otras, y giran entre sí. Debe tener seis para equilibrarse.")
    , PokemonOld((R.drawable.exeggutor), "Exeggutor", "Este Pokémon es muy ruidoso. Esto es debido a que cada una de sus cabezas hace lo que quiere.")
    , PokemonOld((R.drawable.cubone), "Cubone", "Siempre lleva el cráneo de su difunta madre. Su grito hace eco y parece una triste melodía.")
    , PokemonOld((R.drawable.marowak), "Marowak", "Pequeño y débil, este Pokémon siempre va acompañado de su palo de hueso de Pokémon.")
    , PokemonOld((R.drawable.hitmonlee), "Hitmonlee", "Cuando da patadas al enemigo, la planta de sus pies se vuelve tan dura como el diamante.")
    , PokemonOld((R.drawable.hitmonchan), "Hitmonchan", "Sus golpes se asemejan a una taladradora. Puede atravesar un muro de hormigón como si nada.")
    , PokemonOld((R.drawable.lickitung), "Lickitung", "Su lengua mide casi dos metros y se mueve libremente. Sus lametazos pueden causar parálisis.")
    , PokemonOld((R.drawable.koffing), "Koffing", "A veces puede explotar sin avisar, ya que en lugares calurosos su gas interno se expande.")
    , PokemonOld((R.drawable.weezing), "Weezing", "Este Pokémon vive absorbiendo gases venenosos, gérmenes, y el polvo que existe en la basura.")
    , PokemonOld((R.drawable.rhyhorn), "Rhyhorn", "Este Pokémon no tiene muchas luces. Una vez inicia la carga, no para hasta que cae dormido.")
    , PokemonOld((R.drawable.rhydon), "Rhydon", "Camina sobre sus patas traseras, y muestra signos de inteligencia. Es capaz de aguantar lava hirviendo.")
    , PokemonOld((R.drawable.chansey), "Chansey", "Este amable Pokémon es capaz de compartir sus nutrientes huevos con un Pokémon herido.")
    , PokemonOld((R.drawable.tangela), "Tangela", "Se camufla tras una gran masa de enredaderas azules. Se dice que nunca dejan de crecer.")
    , PokemonOld((R.drawable.kangaskhan), "Kangaskhan", "Cuida de su cría en la bolsa de su tripa. No evitará ninguna pelea para protegerla.")
    , PokemonOld((R.drawable.horsea), "Horsea", "Si se siente en peligro, arrojará un potente chorro de agua, o de una tinta especial, por su boca.")
    , PokemonOld((R.drawable.seadra), "Seadra", "Tocar su aleta trasera causa parálisis. Se engancha al coral para mantenerse mientras duerme.")
    , PokemonOld((R.drawable.goldeen), "Goldeen", "En su época de puesta de huevos, suelen ser vistos nadando por ríos contracorriente en grandes grupos.")
    , PokemonOld((R.drawable.seaking), "Seaking", "Este Pokémon hace sus nidos tallando cantos de riachuelo con el cuerno de su cabeza.")
    , PokemonOld((R.drawable.staryu), "Staryu", "Mientras su parte central se mantenga intacta, crecerá de nuevo aunque haya sido destrozado.")
    , PokemonOld((R.drawable.starmie), "Starmie", "Su zona central es conocida como el núcleo. Se piensa que se comunica mediante colores.")
    , PokemonOld((R.drawable.mrmime), "Mr. Mime", "Siempre practica la misma pantomima. Hace creer al enemigo que existe algo que no es real.")
    , PokemonOld((R.drawable.scyther), "Scyther", "Se agazapa en la hierba alta para saltar sobre su enemigo con sus guadañas. Se mueve como un ninja.")
    , PokemonOld((R.drawable.jynx), "Jynx", "Parece moverse como si estuviera bailando un ritmo de su propia creación. Menea mucho sus caderas.")
    , PokemonOld((R.drawable.electabuzz), "Electabuzz", "Cuando hay un apagón, es más que posible que este Pokémon se haya comido la energía.")
    , PokemonOld((R.drawable.magmar), "Magmar", "Nacen en volcanes activos. Su cuerpo parece una gran bola de fuego ya que están en llamas.")
    , PokemonOld((R.drawable.pinsir), "Pinsir", "Atrapa a su presa con sus pinzas, y aprieta fuerte. No se puede mover si hace mucho frío.")
    , PokemonOld((R.drawable.tauros), "Tauros", "Un rudo Pokémon repleto de energía vital. Cuando corre, no para hasta que choca con algo.")
    , PokemonOld((R.drawable.magikarp), "Magikarp", "Famoso por ser poco fiable. Puede encontrarse nadando en mares, lagos, ríos y charcos.")
    , PokemonOld((R.drawable.gyarados), "Gyarados", "Este Pokémon es enormemente destructivo. En la antigüedad, era conocido por destruir ciudades.")
    , PokemonOld((R.drawable.lapras), "Lapras", "Este espíritu gentil es capaz de leer la mente. Puede llevar a la gente a través del mar.")
    , PokemonOld((R.drawable.ditto), "Ditto", "Cuando se fija en un enemigo, su cuerpo se transforma en una copia perfecta del mismo.")
    , PokemonOld((R.drawable.eevee), "Eevee", "Su código genético es muy inestable. Puede evolucionar en diversas razas de Pokémon.")
    , PokemonOld((R.drawable.vaporeon), "Vaporeon", "Su estructura celular se parece a las moléculas de agua. Es invisible cuando está en el agua.")
    , PokemonOld((R.drawable.jolteon), "Jolteon", "Un Pokémon muy sensible. Se entristece o enfada con mucha facilidad, lo que le da energía.")
    , PokemonOld((R.drawable.flareon), "Flareon", "El cuerpo de este Pokémon posee una cámara ígnea. Cuando exhala aire, éste está a 3.000º Celsius.")
    , PokemonOld((R.drawable.porygon), "Porygon", "La gente dice que se trata del único Pokémon que puede volar por el espacio. Aún no lo ha logrado.")
    , PokemonOld((R.drawable.omanyte), "Omanyte", "Este antiguo Pokémon fue recuperado de un fósil. Nada muy bien gracias al movimiento de sus 10 tentáculos.")
    , PokemonOld((R.drawable.omastar), "Omastar", "Picos afilados rodean su boca. Su concha es demasiado grande como para que se mueva libremente.")
    , PokemonOld((R.drawable.kabuto), "Kabuto", "Este Pokémon fue recuperado desde un fósil. Usa los ojos de su espalda al ocultarse en el lecho marino.")
    , PokemonOld((R.drawable.kabutops), "Kabutops", "Este Pokémon es un hábil y rápido nadador. Atrapa a su presa para drenar sus fluidos vitales.")
    , PokemonOld((R.drawable.aerodactyl), "Aerodactyl", "Este Pokémon salvaje, extinto hace siglos, fue resucitado usando ADN tomado de un ámbar.")
    , PokemonOld((R.drawable.snorlax), "Snorlax", "Come cualquier cosa. Incluso la comida pasada de fecha. Su estómago nunca se llena.")
    , PokemonOld((R.drawable.articuno), "Articuno", "Un legendario pájaro Pokémon. Congela el agua que encuentra en el aire para generar nieve.")
    , PokemonOld((R.drawable.zapdos), "Zapdos", "Este legendario pájaro Pokémon solo aparece cuando el cielo se torna oscuro y caen rayos.")
    , PokemonOld((R.drawable.moltres), "Moltres", "Un legendario pájaro Pokémon. Cuando aletea sus flamígeras alas, la oscura noche se torna roja.")
    , PokemonOld((R.drawable.dratini), "Dratini", "La existencia de este Pokémon ha sido confirmada recientemente por un pescador que cogió uno.")
    , PokemonOld((R.drawable.dragonair), "Dragonair", "De acuerdo con un testigo, un aura de extraña forma lo rodea, dándole un misterioso y místico aspecto.")
    , PokemonOld((R.drawable.dragonite), "Dragonite", "Se dice que este Pokémon vive en algún lugar del mar, y que vuela. De todos modos, sólo es un rumor.")
    , PokemonOld((R.drawable.mewtwo), "Mewtwo", "Su ADN es casi el mismo que el de Mew. De todos modos, su tamaño y disposición son diferentes.")
    , PokemonOld((R.drawable.mew), "Mew", "Cuando es mirado a través de un microscopio, puede observarse el delicado pelo de este Pokémon.")
    , PokemonOld((R.drawable.missingno), "MISSINGNO", "Oops, parece que la has liado. Escribe bien el nombre.")
)
/*
data class PokeGif(
    var foto: Int=0,
    var name: String="",
    var desc: String=""
)
var listaGifs : List<PokeGif> = listOf(
    PokeGif((R.drawable.bulbasaur), "Bulbasaur", "Puede sobrevivir largo tiempo sin probar bocado. Guarda energía en el bulbo de su espalda.")
    , PokeGif((R.drawable.ivysaur), "Ivysaur", "Su bulbo crece cuando absorbe energía. Desprende un fuerte aroma cuando florece.")
    , PokeGif((R.drawable.venusaur), "Venusaur", "La flor de su espalda recoge los rayos del sol. Los transforma en energía.")
    , PokeGif((R.drawable.charmander), "Charmander", "La llama en la punta de su cola chisporrotea al arder. Sólo se oye en lugares silenciosos.")
    , PokeGif((R.drawable.charmeleon), "Charmeleon", "Las duras luchas excitan a este Pokémon. Entonces, lanzará llamaradas blanco-azuladas.")
    , PokeGif((R.drawable.charizard), "Charizard", "Cuando lanza una descarga de fuego súper caliente, la roja llama de su cola brilla más intensamente.")
    , PokeGif((R.drawable.squirtle01), "Squirtle", "Lanza agua a su presa desde el agua. Se esconde en su concha cuando se siente en peligro.")
    , PokeGif((R.drawable.wartortle01), "Wartortle", "Si es golpeado, esconderá su cabeza. Aun así, su cola puede seguir golpeando.")
    , PokeGif((R.drawable.blastoise01), "Blastoise", "Cuando ataca a un enemigo, su descarga de agua es aún más potente que una manga de bombero.")
    , PokeGif((R.drawable.caterpie01), "Caterpie", "Si tocas los receptores de su cabeza, soltará un terrible olor para protegerse.")
    , PokeGif((R.drawable.metapod01), "Metapod", "Endurece su concha para protegerse. De todos modos, un gran impacto puede afectarle.")
    , PokeGif((R.drawable.butterfree01), "Butterfree", "Sus alas están cubiertas de polvos venenosos. Como repelen el agua, puede volar bajo la lluvia.")
    , PokeGif((R.drawable.weedle01), "Weedle", "Cuidado con el aguijón venenoso de su cabeza. Se esconde en la hierba y arbustos mientras come.")
    , PokeGif((R.drawable.kakuna01), "Kakuna", "Sólo puede moverse un poco. Cuando está en peligro, envenena a su enemigo con su aguijón.")
    , PokeGif((R.drawable.beedril01), "Beedril", "Tiene 3 aguijones venenosos en sus patas y cola. Suele pinchar a sus enemigos repetidas veces.")
    , PokeGif((R.drawable.pidgey), "Pidgey", "Son muy dóciles. Si son atacados, suelen lanzar arena en lugar de repeler el ataque.")
    , PokeGif((R.drawable.pidgeotto), "Pidgeotto", "Su visión es extraordinaria. Aunque vuele muy alto, detectará todo movimiento de su presa.")
    , PokeGif((R.drawable.pidgeot), "Pidgeot", "Este Pokémon vuela a velocidad Mach 2. Sus grandes garras son armas muy peligrosas.")
    , PokeGif((R.drawable.rattata), "Rattata", "Muerde cualquier cosa con sus colmillos. Si ves uno, seguro que encuentras 40 más en la zona.")
    , PokeGif((R.drawable.raticate), "Raticate", "Sus patas son palmeadas. Sirven de aletas, por lo que puede nadar por ríos en busca de presa.")
    , PokeGif((R.drawable.spearow), "Spearow", "Es incapaz de volar a gran altura, pero es muy rápido, lo que le permite protegerse.")
    , PokeGif((R.drawable.fearow), "Fearow", "Este Pokémon es conocido desde hace muchos años. Si siente peligro volará lejos inmediatamente.")
    , PokeGif((R.drawable.ekans), "Ekans", "Cuanto más viejo, más crece este Pokémon. Por la noche, descansa en las ramas de los árboles.")
    , PokeGif((R.drawable.arbok), "Arbok", "Los espantosos dibujos de su piel han sido estudiados. Seis variaciones han sido confirmadas.")
    , PokeGif((R.drawable.pikachu), "Pikachu", "Mantiene su cola en alto para vigilar. Si das un tirón a su cola, querrá morderte.")
    , PokeGif((R.drawable.raichu), "Raichu", "Cuando la electricidad del cuerpo crece, se vuelve irritable. También brilla en la oscuridad.")
    , PokeGif((R.drawable.sandshrew), "Sandshrew", "Su cuerpo es muy seco. Cuando hace frío por la noche, su piel aparece cubierta con un fino rocío.")
    , PokeGif((R.drawable.sandslash), "Sandslash", "Es muy hábil al golpear a sus enemigos con sus garras. Si se rompen, crecerán en un solo día.")
    , PokeGif((R.drawable.nidoranf), "Nidoran F", "A este Pokémon no le gusta luchar. Pero cuidado, sus pequeños cuernos segregan veneno.")
    , PokeGif((R.drawable.nidorina), "Nidorina", "Cuando descansa profundamente, sus cuernos se contraen. Esto prueba que está relajado.")
    , PokeGif((R.drawable.nidoqueen), "Nidoqueen", "Grandes escamas recubren el duro cuerpo de este Pokémon. Éstas crecen cíclicamente.")
    , PokeGif((R.drawable.nidoranm), "Nidoran M", "Sus largas orejas se mantienen siempre alerta. Si siente peligro, atacará con su venenoso cuerno.")
    , PokeGif((R.drawable.nidorino), "Nidorino", "Sus cuernos contienen veneno. Si se introducen en el cuerpo del enemigo, soltarán su tóxica carga.")
    , PokeGif((R.drawable.nidoking), "Nidoking", "Duro como el acero, posee una poderosa carga. Sus cuernos son tan duros como el diamante.")
    , PokeGif((R.drawable.clefairy), "Clefairy", "Su aspecto jovial y vivaracho lo hace adorable. Piensan que son raros, ya que no son muy comunes.")
    , PokeGif((R.drawable.clefable), "Clefable", "Protege bastante bien su propio entorno. Es una especie de hada, raramente vista por los humanos.")
    , PokeGif((R.drawable.vulpix), "Vulpix", "Su piel y colas son preciosas. Cuando crecen las colas, se dividen formando nuevas colas.")
    , PokeGif((R.drawable.ninetales), "Ninetales", "De acuerdo con una antigua leyenda, este Pokémon es la reencarnación de 9 nobles santos.")
    , PokeGif((R.drawable.jigglypuff), "Jigglypuff", "Utiliza sus misteriosos ojos para engañar a su enemigo. También cantará para dormirlo.")
    , PokeGif((R.drawable.wigglytuff), "Wigglytuff", "Su cuerpo es muy elástico. Cuando inhala aire profundamente, puede inflarse sin límite.")
    , PokeGif((R.drawable.zubat), "Zubat", "Emite sonidos ultrasónicos mientras vuela. Los utiliza como sónar para evitar obstáculos.")
    , PokeGif((R.drawable.golbat), "Golbat", "Ataca de manera violenta sin avisar. Utiliza sus afilados colmillos para chupar sangre.")
    , PokeGif((R.drawable.oddish), "Oddish", "Suele ser confundido con un puñado de semillas. Si lo extraes del suelo, gritará.")
    , PokeGif((R.drawable.gloom), "Gloom", "¡Huele bastante mal! De todas formas, 1 de cada 1000 personas aprecian su fétido olor.")
    , PokeGif((R.drawable.vileplume), "Vileplume", "Aletea sus pétalos de flores para propagar su venenoso polen. El sonido que emite es agudo.")
    , PokeGif((R.drawable.paras), "Paras", "Escarba bajo el suelo para roer las raíces de los árboles. Sus setas absorben sus energías.")
    , PokeGif((R.drawable.parasect), "Parasect", "El parásito absorbe la energía con las setas de la espalda, que lo controlan.")
    , PokeGif((R.drawable.venonat), "Venonat", "Sus grandes ojos actúan como radares. En lugares claros, verás montones de pequeños ojos.")
    , PokeGif((R.drawable.venomoth), "Venomoth", "Es difícil quitar el polvo de sus alas. También posee un veneno que se desprende al contacto.")
    , PokeGif((R.drawable.diglett), "Diglett", "Prefiere los lugares oscuros. Pasa el tiempo bajo tierra, aunque aparece en cuevas.")
    , PokeGif((R.drawable.dugtrio), "Dugtrio", "Un grupo de trillizos que cava a 90 KPH. Por ello, creen que se trata de un terremoto.")
    , PokeGif((R.drawable.meowth), "Meowth", "Parece que son más activos por la noche. Adoran las cosas redondas y brillantes.")
    , PokeGif((R.drawable.persian), "Persian", "¡La gema en su frente brilla por sí misma! Camina con la elegancia de una reina.")
    , PokeGif((R.drawable.psyduck), "Psyduck", "Siempre tiene dolores de cabeza. Posee poderes mentales, pero no sabes cuándo los usará.")
    , PokeGif((R.drawable.golduck), "Golduck", "Sus delgados y largos miembros acaban en anchas aletas. Las usan para nadar en los lagos.")
    , PokeGif((R.drawable.mankey), "Mankey", "Este ágil Pokémon vive en los arboles. Se enfada fácilmente y no dudará en atacar a todos.")
    , PokeGif((R.drawable.primeape), "Primeape", "Sólo se calma cuando nadie está cerca. Llegar a ver ese momento es realmente difícil.")
    , PokeGif((R.drawable.growlithe), "Growlithe", "Este Pokémon es muy amistoso. Aun así, gruñirá a cualquiera que invada su territorio.")
    , PokeGif((R.drawable.arcanine), "Arcanine", "Es un Pokémon legendario en China. Allí, adoran la gracia y belleza que exhibe al correr.")
    , PokeGif((R.drawable.poliwag), "Poliwag", "La dirección de la espiral en el vientre cambia según el área. Prefiere nadar a correr.")
    , PokeGif((R.drawable.poliwhirl), "Poliwhirl", "Cuando lo atacan, usa la espiral del vientre para dormir al rival. Aprovecha para escapar entonces.")
    , PokeGif((R.drawable.poliwrath), "Poliwrath", "Es capaz de nadar usando todos los músculos de su cuerpo. Podrá adelantar incluso a un campeón.")
    , PokeGif((R.drawable.abra), "Abra", "Duerme 18 horas al día. Si siente peligro, se teletransporta a un lugar seguro, aun durmiendo.")
    , PokeGif((R.drawable.kadabra), "Kadabra", "Muchas cosas raras suceden si está cerca. Por ejemplo, hace que los relojes vayan al revés.")
    , PokeGif((R.drawable.alakazam), "Alakazam", "Este Pokémon lo recuerda todo. Nunca olvida lo que aprende. Es un Pokémon muy listo.")
    , PokeGif((R.drawable.machop), "Machop", "Muy poderoso a pesar de su pequeño tamaño. Su maestría en artes marciales lo hace muy duro.")
    , PokeGif((R.drawable.machoke), "Machoke", "El cinturón que rodea su cintura retiene toda su energía. Sin él, este Pokémon sería implacable.")
    , PokeGif((R.drawable.machamp), "Machamp", "Con sólo un brazo puede mover montañas. Usando los cuatro, este Pokémon puede ser terrible.")
    , PokeGif((R.drawable.bellsprout), "Bellsprout", "Prefiere los lugares calientes y húmedos. Atrapa pequeños insectos con sus ramas para devorarlos.")
    , PokeGif((R.drawable.weepinbell), "Weeperbell", "Cuando está hambriento, ataca a todo lo que se mueva. Su pobre presa se derrite en fuertes ácidos.")
    , PokeGif((R.drawable.victreebel), "Victreebel", "Engaña a su presa con un dulce aroma a miel. Una vez atrapada, la presa perderá hasta sus huesos.")
    , PokeGif((R.drawable.tentacool), "Tentacool", "A veces puede ser encontrado seco y medio enterrado en una playa. Al lanzarlo otra vez al mar revivirá.")
    , PokeGif((R.drawable.tentacruel), "Tentacruel", "Puede controlar libremente sus 80 tentáculos. Éstos debilitan a la presa con su poderoso veneno.")
    , PokeGif((R.drawable.geodude), "Geodude", "Se encuentran normalmente en los caminos de montaña. Si te cruzas con uno, se enfadará.")
    , PokeGif((R.drawable.graveler), "Graveler", "Se le suele ver rodando por las montañas. Los obstáculos no los evita. ¡Los arrolla!")
    , PokeGif((R.drawable.golem), "Golem", "Cuando pierde su piel, su cuerpo se vuelve blando y blanquecino. Si esto ocurre, se esconderá.")
    , PokeGif((R.drawable.ponyta), "Ponyta", "Es capaz de saltar muy alto. Con sus pezuñas y sus robustas patas, absorbe el impacto.")
    , PokeGif((R.drawable.rapidash), "Rapidash", "Le encanta correr. Si ve algo más rápido que él, intentará alcanzarlo a toda velocidad.")
    , PokeGif((R.drawable.slowpoke), "Slowpoke", "Es increíblemente lento y perezoso. Le encanta dormir sin preocuparse ni del tiempo ni de lo que ocurra.")
    , PokeGif((R.drawable.slowbro), "Slowbro", "Vive tranquilo en el mar. Si el Shellder de su cola se cae, vuelve a ser un Slowpoke otra vez.")
    , PokeGif((R.drawable.magnemite), "Magnemite", "Puede desafiar a la gravedad desde su nacimiento. Flota en el aire gracias a ondas electromagnéticas.")
    , PokeGif((R.drawable.magneton), "Magneton", "Genera extrañas señales de radio. Es capaz de elevar la temperatura 3º centígrados.")
    , PokeGif((R.drawable.farfetchd), "Farfetch'd", "Vive cerca de las plantas. Son raramente vistos, así que se piensa que se están extinguiendo.")
    , PokeGif((R.drawable.doduo), "Doduo", "Sus cortas alas lo hacen volar con dificultad. De todos modos, puede correr a gran velocidad.")
    , PokeGif((R.drawable.dodrio), "Dodrio", "Una de las dos cabezas de Doduo se divide para formar un nuevo PkMn. Es capaz de correr a 40 KPH.")
    , PokeGif((R.drawable.seel), "Seel", "A este Pokémon le encanta el frío. Le encanta nadar en climas polares, sea cual sea la temperatura.")
    , PokeGif((R.drawable.dewgong), "Dewgong", "Su cuerpo es como una bola de nieve. Inmune al frío intenso, nada rápidamente en aguas heladas.")
    , PokeGif((R.drawable.grimer), "Grimer", "Está hecho de fango endurecido. Huele a pútrido. ¡Por donde pasa, no crece la hierba!")
    , PokeGif((R.drawable.muk), "Muk", "Huele tan mal que puede provocar desmayos. Ha degenerado tanto, que ya ni él mismo se huele.")
    , PokeGif((R.drawable.shellder), "Shellder", "Su concha puede evitar cualquier ataque. El débil cuerpo sólo está expuesto cuando está abierta.")
    , PokeGif((R.drawable.cloyster), "Cloyster", "Utiliza su concha para protegerse. Dicen que es más dura que el diamante. También lanza espinas.")
    , PokeGif((R.drawable.gastly), "Gastly", "Solo aparece en edificios en ruinas. No tiene forma real, ya que parece que está hecho de gas.")
    , PokeGif((R.drawable.haunter), "Haunter", "Toma la vida de su adversario a lengüetazos. Esto produce mareos hasta que la víctima fallece.")
    , PokeGif((R.drawable.gengar), "Gengar", "Sabrás que un Gengar está cerca cuando sufras de sudores fríos. Intentará echarte un hechizo.")
    , PokeGif((R.drawable.onix), "Onix", "Cava a gran velocidad en busca de comida. Los túneles que deja son usados por los Diglett.")
    , PokeGif((R.drawable.drowzee), "Drowzee", "Si duermes cerca de uno todo el tiempo, en alguna ocasión podrás ver sueños que se haya comido antes.")
    , PokeGif((R.drawable.hypno), "Hypno", "Intenta evitar cualquier tipo de contacto visual con este Pokémon. Puede hipnotizar con su péndulo.")
    , PokeGif((R.drawable.krabby), "Krabby", "Sus pinzas son armas perfectas. En alguna ocasión pueden romperse en combate, pero crecerán rápido.")
    , PokeGif((R.drawable.kingler), "Kingler", "Una de sus pinzas crece más que la otra, y es dura como el acero. De todos modos, pesa demasiado.")
    , PokeGif((R.drawable.voltorb), "Voltorb", "Se dice que se camufla como una Poké Ball. Al más mínimo estímulo se autodestruirá.")
    , PokeGif((R.drawable.electrode), "Electrode", "Almacena energía eléctrica en su cuerpo. El más leve shock puede provocar una gran explosión.")
    , PokeGif((R.drawable.exeggcute), "Exeggcute", "Sus cabezas se atraen unas a otras, y giran entre sí. Debe tener seis para equilibrarse.")
    , PokeGif((R.drawable.exeggutor), "Exeggutor", "Este Pokémon es muy ruidoso. Esto es debido a que cada una de sus cabezas hace lo que quiere.")
    , PokeGif((R.drawable.cubone), "Cubone", "Siempre lleva el cráneo de su difunta madre. Su grito hace eco y parece una triste melodía.")
    , PokeGif((R.drawable.marowak), "Marowak", "Pequeño y débil, este Pokémon siempre va acompañado de su palo de hueso de Pokémon.")
    , PokeGif((R.drawable.hitmonlee), "Hitmonlee", "Cuando da patadas al enemigo, la planta de sus pies se vuelve tan dura como el diamante.")
    , PokeGif((R.drawable.hitmonchan), "Hitmonchan", "Sus golpes se asemejan a una taladradora. Puede atravesar un muro de hormigón como si nada.")
    , PokeGif((R.drawable.lickitung), "Lickitung", "Su lengua mide casi dos metros y se mueve libremente. Sus lametazos pueden causar parálisis.")
    , PokeGif((R.drawable.koffing), "Koffing", "A veces puede explotar sin avisar, ya que en lugares calurosos su gas interno se expande.")
    , PokeGif((R.drawable.weezing), "Weezing", "Este Pokémon vive absorbiendo gases venenosos, gérmenes, y el polvo que existe en la basura.")
    , PokeGif((R.drawable.rhyhorn), "Rhyhorn", "Este Pokémon no tiene muchas luces. Una vez inicia la carga, no para hasta que cae dormido.")
    , PokeGif((R.drawable.rhydon), "Rhydon", "Camina sobre sus patas traseras, y muestra signos de inteligencia. Es capaz de aguantar lava hirviendo.")
    , PokeGif((R.drawable.chansey), "Chansey", "Este amable Pokémon es capaz de compartir sus nutrientes huevos con un Pokémon herido.")
    , PokeGif((R.drawable.tangela), "Tangela", "Se camufla tras una gran masa de enredaderas azules. Se dice que nunca dejan de crecer.")
    , PokeGif((R.drawable.kangaskhan), "Kangaskhan", "Cuida de su cría en la bolsa de su tripa. No evitará ninguna pelea para protegerla.")
    , PokeGif((R.drawable.horsea), "Horsea", "Si se siente en peligro, arrojará un potente chorro de agua, o de una tinta especial, por su boca.")
    , PokeGif((R.drawable.seadra), "Seadra", "Tocar su aleta trasera causa parálisis. Se engancha al coral para mantenerse mientras duerme.")
    , PokeGif((R.drawable.goldeen), "Goldeen", "En su época de puesta de huevos, suelen ser vistos nadando por ríos contracorriente en grandes grupos.")
    , PokeGif((R.drawable.seaking), "Seaking", "Este Pokémon hace sus nidos tallando cantos de riachuelo con el cuerno de su cabeza.")
    , PokeGif((R.drawable.staryu), "Staryu", "Mientras su parte central se mantenga intacta, crecerá de nuevo aunque haya sido destrozado.")
    , PokeGif((R.drawable.starmie), "Starmie", "Su zona central es conocida como el núcleo. Se piensa que se comunica mediante colores.")
    , PokeGif((R.drawable.mrmime), "Mr. Mime", "Siempre practica la misma pantomima. Hace creer al enemigo que existe algo que no es real.")
    , PokeGif((R.drawable.scyther), "Scyther", "Se agazapa en la hierba alta para saltar sobre su enemigo con sus guadañas. Se mueve como un ninja.")
    , PokeGif((R.drawable.jynx), "Jynx", "Parece moverse como si estuviera bailando un ritmo de su propia creación. Menea mucho sus caderas.")
    , PokeGif((R.drawable.electabuzz), "Electabuzz", "Cuando hay un apagón, es más que posible que este Pokémon se haya comido la energía.")
    , PokeGif((R.drawable.magmar), "Magmar", "Nacen en volcanes activos. Su cuerpo parece una gran bola de fuego ya que están en llamas.")
    , PokeGif((R.drawable.pinsir), "Pinsir", "Atrapa a su presa con sus pinzas, y aprieta fuerte. No se puede mover si hace mucho frío.")
    , PokeGif((R.drawable.tauros), "Tauros", "Un rudo Pokémon repleto de energía vital. Cuando corre, no para hasta que choca con algo.")
    , PokeGif((R.drawable.magikarp), "Magikarp", "Famoso por ser poco fiable. Puede encontrarse nadando en mares, lagos, ríos y charcos.")
    , PokeGif((R.drawable.gyarados), "Gyarados", "Este Pokémon es enormemente destructivo. En la antigüedad, era conocido por destruir ciudades.")
    , PokeGif((R.drawable.lapras), "Lapras", "Este espíritu gentil es capaz de leer la mente. Puede llevar a la gente a través del mar.")
    , PokeGif((R.drawable.ditto), "Ditto", "Cuando se fija en un enemigo, su cuerpo se transforma en una copia perfecta del mismo.")
    , PokeGif((R.drawable.eevee), "Eevee", "Su código genético es muy inestable. Puede evolucionar en diversas razas de Pokémon.")
    , PokeGif((R.drawable.vaporeon), "Vaporeon", "Su estructura celular se parece a las moléculas de agua. Es invisible cuando está en el agua.")
    , PokeGif((R.drawable.jolteon), "Jolteon", "Un Pokémon muy sensible. Se entristece o enfada con mucha facilidad, lo que le da energía.")
    , PokeGif((R.drawable.flareon), "Flareon", "El cuerpo de este Pokémon posee una cámara ígnea. Cuando exhala aire, éste está a 3.000º Celsius.")
    , PokeGif((R.drawable.porygon), "Porygon", "La gente dice que se trata del único Pokémon que puede volar por el espacio. Aún no lo ha logrado.")
    , PokeGif((R.drawable.omanyte), "Omanyte", "Este antiguo Pokémon fue recuperado de un fósil. Nada muy bien gracias al movimiento de sus 10 tentáculos.")
    , PokeGif((R.drawable.omastar), "Omastar", "Picos afilados rodean su boca. Su concha es demasiado grande como para que se mueva libremente.")
    , PokeGif((R.drawable.kabuto), "Kabuto", "Este Pokémon fue recuperado desde un fósil. Usa los ojos de su espalda al ocultarse en el lecho marino.")
    , PokeGif((R.drawable.kabutops), "Kabutops", "Este Pokémon es un hábil y rápido nadador. Atrapa a su presa para drenar sus fluidos vitales.")
    , PokeGif((R.drawable.aerodactyl), "Aerodactyl", "Este Pokémon salvaje, extinto hace siglos, fue resucitado usando ADN tomado de un ámbar.")
    , PokeGif((R.drawable.snorlax), "Snorlax", "Come cualquier cosa. Incluso la comida pasada de fecha. Su estómago nunca se llena.")
    , PokeGif((R.drawable.articuno), "Articuno", "Un legendario pájaro Pokémon. Congela el agua que encuentra en el aire para generar nieve.")
    , PokeGif((R.drawable.zapdos), "Zapdos", "Este legendario pájaro Pokémon solo aparece cuando el cielo se torna oscuro y caen rayos.")
    , PokeGif((R.drawable.moltres), "Moltres", "Un legendario pájaro Pokémon. Cuando aletea sus flamígeras alas, la oscura noche se torna roja.")
    , PokeGif((R.drawable.dratini), "Dratini", "La existencia de este Pokémon ha sido confirmada recientemente por un pescador que cogió uno.")
    , PokeGif((R.drawable.dragonair), "Dragonair", "De acuerdo con un testigo, un aura de extraña forma lo rodea, dándole un misterioso y místico aspecto.")
    , PokeGif((R.drawable.dragonite), "Dragonite", "Se dice que este Pokémon vive en algún lugar del mar, y que vuela. De todos modos, sólo es un rumor.")
    , PokeGif((R.drawable.mewtwo), "Mewtwo", "Su ADN es casi el mismo que el de Mew. De todos modos, su tamaño y disposición son diferentes.")
    , PokeGif((R.drawable.mew), "Mew", "Cuando es mirado a través de un microscopio, puede observarse el delicado pelo de este Pokémon.")
)

*/
fun busca(poke: String): Int {
    for ((index, pokemon) in listaPoke.withIndex()) {
        if (pokemon.name.lowercase(Locale.ROOT).contains(poke.lowercase(Locale.ROOT))) {
            return index
        }
    };return -1
}